### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by xushengfeng** [cjacker/wl-find-cursor#1]
thank you for this tool!

a error found when i run it:
```
[1]    2152960 segmentation fault (core dumped)  ./wl-find-cursor
```

my desktop is kde Plasma 6.2.4 

I am sorry for my debugging skills, this error seems to appear on line 345, hope it helps you

https://github.com/cjacker/wl-find-cursor/blob/f9d99e1bc99a7b85de0c1a3ba092cb0691190ffe/main.c#L345

**Comment by cjacker** [comment]
Thanks for quickly issue report.

GNOME/KDE didn't implement the wayland virtual-pointer protocol, wl-find-cursor depends on layer-shell and virtual-pointer protocols to get mouse position. these compositors can not be supported until they implement virtual-pointer protocol.

But there is still something need to improve in wl-find-cursor, it SHOULD be able to detect the protocol missing and now it get fixed.

By the way, KDE and GNOME its own way to find the cursor or obtain mouse position. for kwin-wayland, you can run a kwin script to obtain the mouse position:

```
print("Mouse position x=" + workspace.cursorPos.x + " y=" + workspace.cursorPos.y)
```

And, to debug a c program, you can use something like:
```
gdb ./wl-find-cusror
# after load, run it.
>r
# after seg fault, get backtrace
>bt
```
to get more backtrace information in details.
